### PR TITLE
feat: support `requestOptions` prop

### PR DESCRIPTION
**Pull request by VanishMax**
## 📑 Description
Implements #4 – `requestOptions` prop to support request customization.

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by VanishMax** [comment]
@codeacme17 Do I need to build the library and push its output to the repo for this PR?
It seems that `pnpm build:types` exports types differently on my machine than it did before for you.

**Comment by codeacme17** [comment]
Yeah, if it's convenient for you！

**Comment by codeacme17** [comment]
oh sorry, I may need to do some manual work when I package this project, I'll agree to this pr first and then I'll package it. Thank you for your help!

**Comment by codeacme17** [comment]
@VanishMax I sent a request to invite you to become a collaborator on this repo. You can agree to the request if you wish, thanks again for your contribution! and I will close the related issue.

**Comment by VanishMax** [comment]
@codeacme17 Thank you, appreciated

**Pull request merged**
